### ISSUE TITLE
Add theme to Centaur tabs documentation

### ISSUE THREAD

**Issue by ema2159** [cstby/solo-jazz-emacs-theme#3]
Hi! Centaur tabs owner here. Do you mind if I add your theme to `centaur-tabs` supported theme list?

**Comment by cstby** [comment]
EDIT:

Please go right ahead! I'm so sorry, when I read this originally I thought you wanted me to add `centaur-tabs` to my own documentation.

I absolutely love your package, btw. I used to believe that tabs in emacs were unnecessary, but trying `centaur-tabs` totally changes my mind. :)

**Comment by ema2159** [comment]
Perfect! Thanks man! Your theme rocks by the way.
