### ISSUE TITLE
Bold fonts

### ISSUE THREAD

**Issue by cantao** [cstby/solo-jazz-emacs-theme#7]
Hi!

I'm using solo-jazz with Doom Emacs and I have no idea how to (or even if it is possible) to completely disable bold fonts.

Thank you very much!

**Comment by cstby** [comment]
Hi there!

I believe that you can disable bold fonts globally by including `(set-face-bold-p 'bold nil)` in your `init.el` (or the Doom Emacs equivalent). Could you try that out and see if it works for you?

**Comment by cantao** [comment]
No luck :-( I'll leave a message on Doom's issues tracker and see if they have a solution. I'll post here if it works.
Thank you very much!
